# Generated by Django 6.1 on 2026-08-07 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True, verbose_name='Numero Camera')),
                ('is_clean', models.BooleanField(default=True, verbose_name='Pulita')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Occupata')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informazione', models.TextField(verbose_name='Dettaglio')),
                ('is_done', models.BooleanField(default=False, verbose_name='Completato')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='Risposta')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='hotel.hotelroom')),
            ],
        ),
    ]
