# Generated by Django 6.1 on 2026-08-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='is_out_of_order',
            field=models.BooleanField(default=False, verbose_name='Fuori Servizio'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='room_type',
            field=models.CharField(choices=[('SGL', 'Single'), ('DBL', 'Double'), ('TWN', 'Twin'), ('SUI', 'Suite')], default='DBL', max_length=3, verbose_name='Tipo Camera'),
        ),
    ]
